# Generated by Django 5.2.3 on 2025-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preferred_partner_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='project_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='seeking_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='skills_needed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
